### PR TITLE
Student/kamilm changes

### PR DESCRIPTION
**Pull request by Banndzior**
<sub> Mention [stepsize] in a comment if you'd like to report some technical debt. See examples [here](https://app.stepsize.com/api/demo-pr-redirect).</sub>

### CODE REVIEW

**Comment by AndrzejZawadzki** [comment]
ok

**Review by dol568 — APPROVED** [review]

**Review by AndrzejZawadzki — APPROVED** [review]

**Review by LukaszOstapczuk — APPROVED** [review]

**Review by martawas — APPROVED** [review]

**Review by Maciejczuk — APPROVED** [review]

**Review by pogoprojekt — APPROVED** [review]

**Review by owsiej — APPROVED** [review]

**Review by Bociarz1 — COMMENTED** [review]
jest git

**Review by F1shuuu — COMMENTED** [review]
komentarz

**Review by Mateusz7712 — APPROVED** [review]
ok

**Review by AndrzejZawadzki — COMMENTED** [review]
well done

**Pull request merged**
